### ISSUE TITLE
Command extractor crash report

### ISSUE THREAD

**Issue by gsagula** [hedronvision/bazel-compile-commands-extractor#206]
Filling the following issue as per request:
```
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/a089ea60c65490b57e632664954bbd81/execroot/_main/bazel-out/k8-fastbuild/bin/refresh_cc.runfiles/_main/refresh_cc.check_python_version.py", line 15, in <module>
    refresh_cc.main()
  File "/root/.cache/bazel/_bazel_root/a089ea60c65490b57e632664954bbd81/execroot/_main/bazel-out/k8-fastbuild/bin/refresh_cc.py", line 1417, in main
    compile_command_entries.extend(_get_commands(target, flags))
  File "/root/.cache/bazel/_bazel_root/a089ea60c65490b57e632664954bbd81/execroot/_main/bazel-out/k8-fastbuild/bin/refresh_cc.py", line 1279, in _get_commands
    yield from _convert_compile_commands(parsed_aquery_output)
  File "/root/.cache/bazel/_bazel_root/a089ea60c65490b57e632664954bbd81/execroot/_main/bazel-out/k8-fastbuild/bin/refresh_cc.py", line 1159, in _convert_compile_commands
    for source_files, header_files, compile_command_args in outputs:
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.cache/bazel/_bazel_root/a089ea60c65490b57e632664954bbd81/execroot/_main/bazel-out/k8-fastbuild/bin/refresh_cc.py", line 1123, in _get_cpp_command_for_files
    source_files, header_files = _get_files(compile_action)
  File "/root/.cache/bazel/_bazel_root/a089ea60c65490b57e632664954bbd81/execroot/_main/bazel-out/k8-fastbuild/bin/refresh_cc.py", line 627, in _get_files
    assert source_file_candidates, f"No source files found in compile args: {compile_action.arguments}.\nPlease file an issue with this information!"
AssertionError: No source files found in compile args: ['external/bazel_tools~cc_configure_extension~local_config_cc/cc_wrapper.sh', '-xc++-header', '-fsyntax-only', '-U_FORTIFY_SOURCE', '-fstack-protector', '-Wall', '-Wunused-but-set-parameter', '-Wno-free-nonheap-object', '-fno-omit-frame-pointer', '-std=c++14', '-MD', '-MF', 'bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/log/_objs/absl_check/absl_check.h.d', '-iquote', 'external/com_google_absl', '-iquote', 'bazel-out/k8-fastbuild/bin/external/com_google_absl', '-w', '-march=native', '-fPIC', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wunused-variable', '-fdiagnostics-color=always', '-DG2O_USE_VENDORED_CERES=1', '-std=c++20', '-std=c++20', '-Wall', '-Wextra', '-Wcast-qual', '-Wconversion-null', '-Wformat-security', '-Wmissing-declarations', '-Woverlength-strings', '-Wpointer-arith', '-Wundef', '-Wunused-local-typedefs', '-Wunused-result', '-Wvarargs', '-Wvla', '-Wwrite-strings', '-DNOMINMAX', '-Wno-builtin-macro-redefined', '-D__DATE__="redacted"', '-D__TIMESTAMP__="redacted"', '-D__TIME__="redacted"', '-c', 'external/com_google_absl/absl/log/absl_check.h', '-o', 'bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/log/_objs/absl_check/absl_check.h.processed'].
Please file an issue with this information!
```

**Comment by rockwotj** [comment]
Duplicate of https://github.com/hedronvision/bazel-compile-commands-extractor/issues/199
