### ISSUE TITLE
New `parse_headers` feature breaks generation

### ISSUE THREAD

**Issue by keith** [hedronvision/bazel-compile-commands-extractor#211]
```
Traceback (most recent call last):
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/6b14d4c6387320db4445b1f7e9639459/execroot/_main/bazel-out/k8-fastbuild-default/bin/refresh_compile_commands.runfiles/_main/refresh_compile_commands.check_python_version.py", line 15, in <module>
    refresh_compile_commands.main()
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/6b14d4c6387320db4445b1f7e9639459/execroot/_main/bazel-out/k8-fastbuild-default/bin/refresh_compile_commands.runfiles/_main/refresh_compile_commands.py", line 1426, in main
    compile_command_entries.extend(_get_commands(args.bazel, target, flags, passthrough_flags))
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/6b14d4c6387320db4445b1f7e9639459/execroot/_main/bazel-out/k8-fastbuild-default/bin/refresh_compile_commands.runfiles/_main/refresh_compile_commands.py", line 1282, in _get_commands
    yield from _convert_compile_commands(bazel, parsed_aquery_output)
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/6b14d4c6387320db4445b1f7e9639459/execroot/_main/bazel-out/k8-fastbuild-default/bin/refresh_compile_commands.runfiles/_main/refresh_compile_commands.py", line 1162, in _convert_compile_commands
    for source_files, header_files, compile_command_args in outputs:
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/6b14d4c6387320db4445b1f7e9639459/external/rules_python~~python~python_3_11_x86_64-unknown-linux-gnu/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/6b14d4c6387320db4445b1f7e9639459/external/rules_python~~python~python_3_11_x86_64-unknown-linux-gnu/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/6b14d4c6387320db4445b1f7e9639459/external/rules_python~~python~python_3_11_x86_64-unknown-linux-gnu/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/6b14d4c6387320db4445b1f7e9639459/external/rules_python~~python~python_3_11_x86_64-unknown-linux-gnu/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/6b14d4c6387320db4445b1f7e9639459/external/rules_python~~python~python_3_11_x86_64-unknown-linux-gnu/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/6b14d4c6387320db4445b1f7e9639459/execroot/_main/bazel-out/k8-fastbuild-default/bin/refresh_compile_commands.runfiles/_main/refresh_compile_commands.py", line 1126, in _get_cpp_command_for_files
    source_files, header_files = _get_files(bazel, compile_action)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/.cache/bazel/_bazel_ubuntu/6b14d4c6387320db4445b1f7e9639459/execroot/_main/bazel-out/k8-fastbuild-default/bin/refresh_compile_commands.runfiles/_main/refresh_compile_commands.py", line 630, in _get_files
    assert source_file_candidates, f"No source files found in compile args: {compile_action.arguments}.\nPlease file an issue with this information!"
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: No source files found in compile args: ['external/bazel_tools~cc_configure_extension~local_config_cc/cc_wrapper.sh', '-xc++-header', '-fsyntax-only', '-U_FORTIFY_SOURCE', '-fstack-protector', '-Wall', '-Wthread-safety', '-Wself-assign', '-Wunused-but-set-parameter', '-Wno-free-nonheap-object', '-fcolor-diagnostics', '-fno-omit-frame-pointer', '-std=c++14', '-MD', '-MF', 'bazel-out/k8-fastbuild-default/bin/external/abseil-cpp~/absl/strings/_objs/cord/cord.h.d', '-iquote', 'external/abseil-cpp~', '-iquote', 'bazel-out/k8-fastbuild-default/bin/external/abseil-cpp~', '-fdata-sections', '-ffunction-sections', '-fno-exceptions', '-fno-rtti', '-funwind-tables', '-fvisibility-inlines-hidden', '-fvisibility=hidden', '-UNDEBUG', '-D_DEBUG', '-D_GLIBCXX_ASSERTIONS', '-Wall', '-Wextra', '-Wno-unused-parameter', '-Wwrite-strings', '-Wcast-qual', '-Wmissing-field-initializers', '-pedantic', '-Wno-long-long', '-Wimplicit-fallthrough', '-Wcovered-switch-default', '-Wno-noexcept-type', '-Wnon-virtual-dtor', '-Wdelete-non-virtual-dtor', '-Wsuggest-override', '-Wstring-conversion', '-Wmisleading-indentation', '-Wctad-maybe-unsupported', '-Wno-c++17-attribute-extensions', '-Wno-c++20-attribute-extensions', '-Wno-gnu-zero-variadic-macro-arguments', '-Wno-gnu-statement-expression-from-macro-expansion', '-Wno-gcc-compat', '-Wno-dollar-in-identifier-extension', '-Wno-strict-prototypes', '-ffile-compilation-dir=.', '-Werror=incomplete-umbrella', '-Werror=global-constructors', '-O2', '-g', '-std=c++17', '-Wall', '-Wextra', '-Wcast-qual', '-Wconversion', '-Wfloat-overflow-conversion', '-Wfloat-zero-conversion', '-Wfor-loop-analysis', '-Wformat-security', '-Wgnu-redeclared-enum', '-Winfinite-recursion', '-Winvalid-constexpr', '-Wliteral-conversion', '-Wmissing-declarations', '-Woverlength-strings', '-Wpointer-arith', '-Wself-assign', '-Wshadow-all', '-Wshorten-64-to-32', '-Wsign-conversion', '-Wstring-conversion', '-Wtautological-overlap-compare', '-Wtautological-unsigned-zero-compare', '-Wundef', '-Wuninitialized', '-Wunreachable-code', '-Wunused-comparison', '-Wunused-local-typedefs', '-Wunused-result', '-Wvla', '-Wwrite-strings', '-Wno-float-conversion', '-Wno-implicit-float-conversion', '-Wno-implicit-int-float-conversion', '-Wno-unknown-warning-option', '-DNOMINMAX', '-Wno-global-constructors', '-no-pedantic', '-Werror', '-Wno-covered-switch-default', '-Wno-implicit-fallthrough', '-Wno-cast-qual', '-Wno-sign-compare', '-Wno-deprecated-declarations', '-no-canonical-prefixes', '-Wno-builtin-macro-redefined', '-D__DATE__="redacted"', '-D__TIMESTAMP__="redacted"', '-D__TIME__="redacted"', '-c', 'external/abseil-cpp~/absl/strings/cord.h', '-o', 'bazel-out/k8-fastbuild-default/bin/external/abseil-cpp~/absl/strings/_objs/cord/cord.h.processed'].
Please file an issue with this information!
```

Fixed with `--features=-parse_headers --host_features=-parse_headers`

**Comment by dotnwat** [comment]
same issue here. thanks for the workaround
