### ISSUE TITLE
When building abseil library: AssertionError: No source files found in compile args 

### ISSUE THREAD

**Issue by tintor** [hedronvision/bazel-compile-commands-extractor#229]
Traceback (most recent call last):
  File "/home/marko/.cache/bazel/_bazel_marko/0ce0fa6fc07580e57fc58b0bf75cd1e8/execroot/_main/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/_main/refresh_compile_commands.check_python_version.py", line 15, in <module>
    refresh_compile_commands.main()
  File "/home/marko/.cache/bazel/_bazel_marko/0ce0fa6fc07580e57fc58b0bf75cd1e8/execroot/_main/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/_main/refresh_compile_commands.py", line 1419, in main
    compile_command_entries.extend(_get_commands(target, flags))
  File "/home/marko/.cache/bazel/_bazel_marko/0ce0fa6fc07580e57fc58b0bf75cd1e8/execroot/_main/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/_main/refresh_compile_commands.py", line 1281, in _get_commands
    yield from _convert_compile_commands(parsed_aquery_output)
  File "/home/marko/.cache/bazel/_bazel_marko/0ce0fa6fc07580e57fc58b0bf75cd1e8/execroot/_main/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/_main/refresh_compile_commands.py", line 1161, in _convert_compile_commands
    for source_files, header_files, compile_command_args in outputs:
  File "/home/marko/.cache/bazel/_bazel_marko/0ce0fa6fc07580e57fc58b0bf75cd1e8/external/rules_python~~python~python_3_11_x86_64-unknown-linux-gnu/lib/python3.11/concurrent/futures/_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marko/.cache/bazel/_bazel_marko/0ce0fa6fc07580e57fc58b0bf75cd1e8/external/rules_python~~python~python_3_11_x86_64-unknown-linux-gnu/lib/python3.11/concurrent/futures/_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/marko/.cache/bazel/_bazel_marko/0ce0fa6fc07580e57fc58b0bf75cd1e8/external/rules_python~~python~python_3_11_x86_64-unknown-linux-gnu/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/marko/.cache/bazel/_bazel_marko/0ce0fa6fc07580e57fc58b0bf75cd1e8/external/rules_python~~python~python_3_11_x86_64-unknown-linux-gnu/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/marko/.cache/bazel/_bazel_marko/0ce0fa6fc07580e57fc58b0bf75cd1e8/external/rules_python~~python~python_3_11_x86_64-unknown-linux-gnu/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marko/.cache/bazel/_bazel_marko/0ce0fa6fc07580e57fc58b0bf75cd1e8/execroot/_main/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/_main/refresh_compile_commands.py", line 1125, in _get_cpp_command_for_files
    source_files, header_files = _get_files(compile_action)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marko/.cache/bazel/_bazel_marko/0ce0fa6fc07580e57fc58b0bf75cd1e8/execroot/_main/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/_main/refresh_compile_commands.py", line 629, in _get_files
    assert source_file_candidates, f"No source files found in compile args: {compile_action.arguments}.\nPlease file an issue with this information!"
           ^^^^^^^^^^^^^^^^^^^^^^
AssertionError: No source files found in compile args: ['external/bazel_tools~cc_configure_extension~local_config_cc/cc_wrapper.sh', '-xc++-header', '-fsyntax-only', '-U_FORTIFY_SOURCE', '-fstack-protector', '-Wall', '-Wthread-safety', '-Wself-assign', '-Wunused-but-set-parameter', '-Wno-free-nonheap-object', '-fcolor-diagnostics', '-fno-omit-frame-pointer', '-std=c++14', '-MD', '-MF', 'bazel-out/k8-fastbuild/bin/external/abseil-cpp~/absl/container/_objs/flat_hash_set/flat_hash_set.h.d', '-iquote', 'external/abseil-cpp~', '-iquote', 'bazel-out/k8-fastbuild/bin/external/abseil-cpp~', '-mavx2', '-std=c++23', '-Wfatal-errors', '-stdlib=libc++', '-Wall', '-Wextra', '-Wc++98-compat-extra-semi', '-Wcast-qual', '-Wconversion', '-Wdeprecated-pragma', '-Wfloat-overflow-conversion', '-Wfloat-zero-conversion', '-Wfor-loop-analysis', '-Wformat-security', '-Wgnu-redeclared-enum', '-Winfinite-recursion', '-Winvalid-constexpr', '-Wliteral-conversion', '-Wmissing-declarations', '-Woverlength-strings', '-Wpointer-arith', '-Wself-assign', '-Wshadow-all', '-Wshorten-64-to-32', '-Wsign-conversion', '-Wstring-conversion', '-Wtautological-overlap-compare', '-Wtautological-unsigned-zero-compare', '-Wundef', '-Wuninitialized', '-Wunreachable-code', '-Wunused-comparison', '-Wunused-local-typedefs', '-Wunused-result', '-Wvla', '-Wwrite-strings', '-Wno-float-conversion', '-Wno-implicit-float-conversion', '-Wno-implicit-int-float-conversion', '-Wno-unknown-warning-option', '-DNOMINMAX', '-no-canonical-prefixes', '-Wno-builtin-macro-redefined', '-D__DATE__="redacted"', '-D__TIMESTAMP__="redacted"', '-D__TIME__="redacted"', '-c', 'external/abseil-cpp~/absl/container/flat_hash_set.h', '-o', 'bazel-out/k8-fastbuild/bin/external/abseil-cpp~/absl/container/_objs/flat_hash_set/flat_hash_set.h.processed'].
Please file an issue with this information!

**Comment by jashank** [comment]
This sounds like the same issue as #199. Proposed fix: #219. Workaround: downgrade from Bazel 7.2.x to 7.1.x.
