### ISSUE TITLE
AssertionError: No source files found in compile args

### ISSUE THREAD

**Issue by sthornington** [hedronvision/bazel-compile-commands-extractor#234]
This resulted from the latest version of `rules_rust` adding a dependency on google protobuf (and transitively abseil therefore), as part of their work here https://github.com/bazelbuild/rules_rust/pull/3037#discussion_r1875117024.  Since we already have our own fork of bazel-compile-commands-extractor, I'm going to try to work around locally, but I filed this because the assertion asked me to.

```
Traceback (most recent call last):
  File "/scratch/simont/bazel_base/baabe75813de12a265f0541a9f99347d/execroot/__main__/bazel-out/k8-dbg/bin/refresh_compile_commands.runfiles/__main__/refresh_compile_commands.check_python_version.py", line 15, in <module>
    refresh_compile_commands.main()
  File "/scratch/simont/bazel_base/baabe75813de12a265f0541a9f99347d/execroot/__main__/bazel-out/k8-dbg/bin/refresh_compile_commands.py", line 1807, in main
    compile_command_entries.extend(_get_commands(target, flags))
  File "/scratch/simont/bazel_base/baabe75813de12a265f0541a9f99347d/execroot/__main__/bazel-out/k8-dbg/bin/refresh_compile_commands.py", line 1631, in _get_commands
    yield from _convert_compile_commands(parsed_aquery_output)
  File "/scratch/simont/bazel_base/baabe75813de12a265f0541a9f99347d/execroot/__main__/bazel-out/k8-dbg/bin/refresh_compile_commands.py", line 1486, in _convert_compile_commands
    for source_files, header_files, compile_command_args in outputs:
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/scratch/simont/bazel_base/baabe75813de12a265f0541a9f99347d/execroot/__main__/bazel-out/k8-dbg/bin/refresh_compile_commands.py", line 1448, in _get_cpp_command_for_files
    source_files, header_files = _get_files(compile_action)
  File "/scratch/simont/bazel_base/baabe75813de12a265f0541a9f99347d/execroot/__main__/bazel-out/k8-dbg/bin/refresh_compile_commands.py", line 755, in _get_files
    assert (
AssertionError: No source files found in compile args: ['external/local_config_cc/cc_wrapper.sh', '-xc++-header', '-fsyntax-only', '-U_FORTIFY_SOURCE', '-fstack-protector', '-Wall', '-Wunused-but-set-parameter', '-Wno-free-nonheap-object', '-fno-omit-frame-pointer', '-g0', '-O2', '-D_FORTIFY_SOURCE=1', '-DNDEBUG', '-ffunction-sections', '-fdata-sections', '-std=c++14', '-MD', '-MF', 'bazel-out/k8-opt-exec-ST-a828a81199fe/bin/external/com_google_absl/absl/log/_objs/initialize/initialize.h.d', '-iquote', 'external/com_google_absl', '-iquote', 'bazel-out/k8-opt-exec-ST-a828a81199fe/bin/external/com_google_absl', '-g0', '-g0', '-Wall', '-Wextra', '-Wcast-qual', '-Wconversion-null', '-Wformat-security', '-Wmissing-declarations', '-Woverlength-strings', '-Wpointer-arith', '-Wundef', '-Wunused-local-typedefs', '-Wunused-result', '-Wvarargs', '-Wvla', '-Wwrite-strings', '-DNOMINMAX', '-Wno-builtin-macro-redefined', '-D__DATE__="redacted"', '-D__TIMESTAMP__="redacted"', '-D__TIME__="redacted"', '-c', 'external/com_google_absl/absl/log/initialize.h', '-o', 'bazel-out/k8-opt-exec-ST-a828a81199fe/bin/external/com_google_absl/absl/log/_objs/initialize/initialize.h.processed'].
Please file an issue with this information!
```

**Comment by davidzchen** [comment]
Possible duplicate of #199.
