### ISSUE TITLE
Individual Setup Issues

### ISSUE THREAD

**Issue by gargeesuresh** [hedronvision/bazel-compile-commands-extractor#42]
I'm following the usage instructions from your repo's README.md, 

- Completed the WORKSPACE setup 
- Tried both of the common paths to get the extractor running ( both of them gave me no output compile_commands.json file)
- I have added this to my build file, sh-edge being one of the targets that need to be built. How can I change this if I'd like to build all targets within the build directory?
```
load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")

refresh_compile_commands(
    name = "refresh_compile_commands",

    # Specify the targets of interest.
    # For example, specify a dict of targets and any flags required to build.
    # (No need to add flags already in .bazelrc. They're automatically picked up.)
    targets = {
      #"//:my_output_1": "--important_flag1 --important_flag2=true", 
      #"//:my_output_2": "",
      ":sh-edge": "--config linux64 --config beta --experimental_scale_timeouts=3.0",
       #sh-edge being one of the targets that need to be built. How can I change this if I'd like to build all targets within the build 
       #directory?
    },
    # If you don't need flags, a list of targets is also okay, as is a single target string.
    # For more details, feel free to look into refresh_compile_commands.bzl if you want.
)
``` 

- got clangd's extension installed and configured according to the given instructions.

After the above configuration, running a bazel build command, gives a successful build, `INFO: Build completed successfully`,however I'm unable to find the compile_commands.json file.

**Comment by cpsauer** [comment]
Hi, Gargee,

Thanks for stopping by and giving it a shot. Sorry it isn't all working as we'd expect. Let's figure out together what's going on!

I think we should first handle the issue of no `compile_commands.json` being generated, since that's the strangest part.

I'm taking that to mean that there's no `compile_commands.json` file--and that there aren't any runtime errors either--just that `INFO: Build completed successfully` message. Please correct me if that's wrong! It should be creating a compile_commands.json in your WORKSPACE root, right next to the WORKSPACE file. (I think this might be what you're referring to as "the build directory"?)


If you `bazel run @hedron_compile_commands//:refresh_all`
do you see messages like the following, usually logged in blue and green, as the extractor runs? 
```
>>> Analyzing commands used in @//...
>>> Finished extracting commands for @//...
```
I want to make sure you're not just **building** the extractor but **running** it, too.

Could you confirm? If that doesn't work, I'd love it if you'd copy-paste what you ran in your terminal and what the output was so I can take a peek.


--- 

> How can I change this if I'd like to build all targets within the build directory?

I think you're asking how to extract commands from all targets in the bazel workspace--and specify the same flags for all of them. Is that right? If so, you can do, e.g.:

```starlark
refresh_compile_commands(
    name = "refresh_compile_commands",
    targets = {
      "//...": "--config linux64 --config beta --experimental_scale_timeouts=3.0",
    },
)
```

> Wildcard target patterns (..., *, :all) patterns are allowed, like in bazel build. 
>    For more, see https://docs.bazel.build/versions/main/guide.html#specifying-targets-to-build

If you'd ever like more docs on refresh_compile_commands, there are some good ones at the top of [refresh_compile_commands.bzl](https://github.com/hedronvision/bazel-compile-commands-extractor/blob/main/refresh_compile_commands.bzl).

And note again that you have to `bazel run :refresh_compile_commands`.

---

I'll also proactively update the readme and docs to try to reduce future problems around these lines. Thanks for your feedback! It's a gift.

Looking forward to hearing back.

Chris

**Comment by gargeesuresh** [comment]
Thank you for the help Chris!

- I have modified the BUILD file with Wildcard target patterns. 
- On Running both `bazel run :refresh_compile_commands` and `bazel run @hedron_compile_commands//:refresh_all`
I get a similar output with a successful build, and a Type error following `>>> Analyzing commands used in @//...`

Here's the output of running `bazel run :refresh_compile_commands`
```
DEBUG: Rule 'hedron_compile_commands' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "ce5714be202e942ba5f404d1c373a2fbb4b88c66737a924491fbd49afa91d48b"
DEBUG: Repository hedron_compile_commands instantiated at:
  /home/ess/fold/WORKSPACE:219:13: in <toplevel>
Repository rule http_archive defined at:
  /home/ess/.cache/bazel/_bazel_ess/fa94a02d46b0b18439dcda253df7b892/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
gobuild-deps: Using target: fold-bazel-deps
gobuild-deps: Using buildtype: beta
gobuild-deps: Using source root: /home/ess/.cache/bazel/_bazel_ess/fa94a02d46b0b18439dcda253df7b892/external/gobuild_support_target/
gobuild-deps: Using local component cache: /home/ess/.cache/bazel/_bazel_ess/fa94a02d46b0b18439dcda253df7b892/external/.compcache
gobuild-deps: Using target: fold-bazel-deps
gobuild-deps: Using buildtype: beta
gobuild-deps: Using source root: /home/ess/.cache/bazel/_bazel_ess/fa94a02d46b0b18439dcda253df7b892/external/gobuild_support_target/
gobuild-deps: Using local component cache: /home/ess/.cache/bazel/_bazel_ess/fa94a02d46b0b18439dcda253df7b892/external/.compcache
gobuild-deps: warning: Failed to get FQDN, using computer name instead
gobuild-deps: Loading component dependency information...
gobuild-deps: warning: Failed to get FQDN, using computer name instead
gobuild-deps: Loading component dependency information...
gobuild-deps: Using hosttype: linux-centos72-gc32-1
gobuild-deps: Using hosttype: linux-centos72-gc32-1
gobuild-deps: warning: Failed to get FQDN, using computer name instead
gobuild-deps: warning: Failed to get FQDN, using computer name instead
gobuild-deps: Component cache status:
gobuild-deps: ----------------------------------------------------------------------------------------------------------------------------------
gobuild-deps: NAME                       BRANCH       CLN                                       BUILDTYPE  BUILDNUM  STATUS     HAVE?  SHAREABLE
gobuild-deps: cayman_esx_toolchain_gcc6  gcc6  4926b3e84b51f4bce7753bc4ea8aabc10e4490df  release    8601295   succeeded  True   False    
gobuild-deps: ----------------------------------------------------------------------------------------------------------------------------------
gobuild-deps: Component cache status:
gobuild-deps: --------------------------------------------------------------------------------------------------------------------------------
gobuild-deps: NAME               BRANCH             CLN                                       BUILDTYPE  BUILDNUM  STATUS     HAVE?  SHAREABLE
gobuild-deps: cayman_glibc_2_17  glibc-2.17  16b95f19da278ba4707fe54b061669890377fe84  release    18711896  succeeded  True   False    
gobuild-deps: --------------------------------------------------------------------------------------------------------------------------------
gobuild-deps: All components downloaded and ready.
@cayman_esx_toolchain_gcc6,/home/ess/.cache/bazel/_bazel_ess/fa94a02d46b0b18439dcda253df7b892/external/.compcache/cayman_esx_toolchain/ob-8601295/linux64
gobuild-deps: All components downloaded and ready.
@cayman_glibc_2_17,/home/ess/.cache/bazel/_bazel_ess/fa94a02d46b0b18439dcda253df7b892/external/.compcache/cayman_esx_glibc/ob-18711896/linux64
INFO: Analyzed target //security/security-hub/cpp:refresh_compile_commands (41 packages loaded, 6004 targets configured).
INFO: Found 1 target...
Target //security/security-hub/cpp:refresh_compile_commands up-to-date:
  fold-bin/security/security-hub/cpp/refresh_compile_commands.py
  fold-bin/security/security-hub/cpp/refresh_compile_commands
INFO: Elapsed time: 60.586s, Critical Path: 0.09s
INFO: 2 processes: 2 internal.
INFO: Build completed successfully, 2 total actions
INFO: Build completed successfully, 2 total actions
>>> Analyzing commands used in //security/security-hub/cpp/...
Traceback (most recent call last):
  File "/home/ess/.cache/bazel/_bazel_ess/fa94a02d46b0b18439dcda253df7b892/execroot/fold/bazel-out/k8-fastbuild/bin/security/security-hub/cpp/refresh_compile_commands.runfiles/fold/security/security-hub/cpp/refresh_compile_commands.py", line 332, in <module>
    compile_command_entries.extend(_get_commands(target, flags))
  File "/home/ess/.cache/bazel/_bazel_ess/fa94a02d46b0b18439dcda253df7b892/execroot/fold/bazel-out/k8-fastbuild/bin/security/security-hub/cpp/refresh_compile_commands.runfiles/fold/security/security-hub/cpp/refresh_compile_commands.py", line 295, in _get_commands
    check=False, # We explicitly ignore errors from `bazel aquery` and carry on.
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```
Here's the output of running `bazel run @hedron_compile_commands//:refresh_all`
```  
DEBUG: Rule 'hedron_compile_commands' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "ce5714be202e942ba5f404d1c373a2fbb4b88c66737a924491fbd49afa91d48b"
DEBUG: Repository hedron_compile_commands instantiated at:
  /home/ess/fold/WORKSPACE:219:13: in <toplevel>
Repository rule http_archive defined at:
  /home/ess/.cache/bazel/_bazel_ess/fa94a02d46b0b18439dcda253df7b892/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
INFO: Analyzed target @hedron_compile_commands//:refresh_all (0 packages loaded, 2 targets configured).
INFO: Found 1 target...
Target @hedron_compile_commands//:refresh_all up-to-date:
  fold-bin/external/hedron_compile_commands/refresh_all.py
  fold-bin/external/hedron_compile_commands/refresh_all
INFO: Elapsed time: 0.499s, Critical Path: 0.02s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
>>> Analyzing commands used in @//...
Traceback (most recent call last):
  File "/home/ess/.cache/bazel/_bazel_ess/fa94a02d46b0b18439dcda253df7b892/execroot/fold/bazel-out/k8-fastbuild/bin/external/hedron_compile_commands/refresh_all.runfiles/hedron_compile_commands/refresh_all.py", line 332, in <module>
    compile_command_entries.extend(_get_commands(target, flags))
  File "/home/ess/.cache/bazel/_bazel_ess/fa94a02d46b0b18439dcda253df7b892/execroot/fold/bazel-out/k8-fastbuild/bin/external/hedron_compile_commands/refresh_all.runfiles/hedron_compile_commands/refresh_all.py", line 295, in _get_commands
    check=False, # We explicitly ignore errors from `bazel aquery` and carry on.
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
File "/usr/lib/python3.6/subprocess.py", line 423, in run
with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

**Comment by cpsauer** [comment]
Whoa! Okay. Yeah.

So to start, let's get you a newer Python version and the newest version of this tool.  

[I can see you have Python 3.6 from the paths in the output above. And for quite a while, this tool has printed a an error message when you use Python <3.7. So I know you're using a fairly old version of this tool.]

Then let me know how it works! (Pasting console output if you need to.)

**Comment by gargeesuresh** [comment]
Thank you!

- Have upgraded to Python3.9
- On running  `bazel run @hedron_compile_commands//:refresh_all` Build fails, 
- On running 'bazel run :refresh_compile_commands`, I get the following output
```
INFO: Build completed successfully, 1 total action
>>> Analyzing commands used in //security/security-hub/cpp/...
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
ERROR: An error occurred during the fetch of repository 'sdks_deps':
   Traceback (most recent call last):
	File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/python/legacy_pip_import/pip.bzl", line 59, column 13, in _pip_import_impl
		fail("pip_import failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: pip_import failed:  (Exception:
Traceback (most recent call last):
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/commands/wheel.py", line 163, in run
    with self._build_session(options) as session:
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/basecommand.py", line 66, in _build_session
    session = PipSession(
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/_vendor/distro.py", line 1050, in <module>
    _distro = LinuxDistribution()
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/_vendor/distro.py", line 593, in __init__
    self._lsb_release_info = self._get_lsb_release_info() \
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/_vendor/distro.py", line 931, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout, stderr)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1.
)
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/python/legacy_pip_import/pip.bzl", line 59, column 13, in _pip_import_impl
		fail("pip_import failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: pip_import failed:  (Exception:
Traceback (most recent call last):
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/commands/wheel.py", line 163, in run
    with self._build_session(options) as session:
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/basecommand.py", line 66, in _build_session
    session = PipSession(
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/_vendor/distro.py", line 1050, in <module>
    _distro = LinuxDistribution()
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/_vendor/distro.py", line 593, in __init__
    self._lsb_release_info = self._get_lsb_release_info() \
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/_vendor/distro.py", line 931, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout, stderr)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1.
)
ERROR: no such package '@sdks_deps//': pip_import failed:  (Exception:
Traceback (most recent call last):
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/commands/wheel.py", line 163, in run
    with self._build_session(options) as session:
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/basecommand.py", line 66, in _build_session
    session = PipSession(
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/_vendor/distro.py", line 1050, in <module>
    _distro = LinuxDistribution()
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/_vendor/distro.py", line 593, in __init__
    self._lsb_release_info = self._get_lsb_release_info() \
  File "/home/gargee/.cache/bazel/_bazel_gargee/d32782c503323e3dc286879a88bb0585/external/rules_python/tools/piptool.par/piptool_deps_pypi__pip_9_0_3/pip/_vendor/distro.py", line 931, in _get_lsb_release_info
    raise subprocess.CalledProcessError(code, cmd, stdout, stderr)
subprocess.CalledProcessError: Command 'lsb_release -a' returned non-zero exit status 1.
)
aquery failed. Command: bazel aquery 'mnemonic('"'"'(Objc|Cpp)Compile'"'"',deps(//security/security-hub/cpp/...))' --output=jsonproto --ui_event_filters=-info --noshow_progress --config linux64 --config beta --experimental_scale_timeouts=3.0
>>> Failed extracting commands for //security/security-hub/cpp/...
    Continuing gracefully...
```

**Comment by cpsauer** [comment]
Hey, Gargee.

I'd love to help get this tool working for you, but that output looks more like some  like a Bazel setup problem of some kind. That's Bazel's python internals crashing, right? 

Can you build and run normal py_binary? Does `bazel aquery "mnemonic('CppCompile',//...)"` run cleanly? If either don't, then we've got to get your Bazel/Python install squared away first.

All the best,
Chris

**Comment by gargeesuresh** [comment]
Hey Chris, 

I will ask for help in bazel/python forums and get this issue sorted. Thank you for the help!

Thanks, 
Gargee
