### ISSUE TITLE
The command failed to output compile_commands.json

### ISSUE THREAD

**Issue by lsmgeb89** [hedronvision/bazel-compile-commands-extractor#60]
I am trying to use it in my workspace.
I modified the top-level `BUILD.bazel` file to add `refresh_compile_commands` as suggested in case 3.
After running `bazel run :refresh_compile_commands`, it shows the following errors.
I have masked the name related to my workspace by using `xxx`, `yyy` and etc.

```text
Traceback (most recent call last):
  File "/home/xxx/.cache/bazel/_bazel_xxx/eebe212d3d0401f0e0780e090816ed4f/execroot/main_heads_yyy/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/main_heads_yyy/refresh_compile_commands.py", line 813, in <module>
    compile_command_entries.extend(_get_commands(target, flags))
  File "/home/xxx/.cache/bazel/_bazel_xxx/eebe212d3d0401f0e0780e090816ed4f/execroot/main_heads_yyy/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/main_heads_yyy/refresh_compile_commands.py", line 709, in _get_commands
    yield from _convert_compile_commands(parsed_aquery_output)
  File "/home/xxx/.cache/bazel/_bazel_xxx/eebe212d3d0401f0e0780e090816ed4f/execroot/main_heads_yyy/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/main_heads_yyy/refresh_compile_commands.py", line 627, in _convert_compile_commands
    for source_files, header_files, compile_command_args in outputs:
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/xxx/.cache/bazel/_bazel_xxx/eebe212d3d0401f0e0780e090816ed4f/execroot/main_heads_yyy/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/main_heads_yyy/refresh_compile_commands.py", line 585, in _get_cpp_command_for_files
    source_files, header_files = _get_files(compile_action)
  File "/home/xxx/.cache/bazel/_bazel_xxx/eebe212d3d0401f0e0780e090816ed4f/execroot/main_heads_yyy/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/main_heads_yyy/refresh_compile_commands.py", line 487, in _get_files
    return {source_file}, _get_headers(compile_action, source_file) if file_exists else set()
  File "/home/xxx/.cache/bazel/_bazel_xxx/eebe212d3d0401f0e0780e090816ed4f/execroot/main_heads_yyy/bazel-out/k8-fastbuild/bin/refresh_compile_commands.runfiles/main_heads_yyy/refresh_compile_commands.py", line 420, in _get_headers
    action_key, headers = json.load(cache_file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Thanks.

**Comment by cpsauer** [comment]
Hey @lsmgeb89! Thanks for giving this tool a try. I really appreciate your writing in when things are being annoying here--and I'm sorry they are. Let's get it sorted.

I'm going to focus on this one first, and then we'll get back to the .gitignore

Gimme a sec to parse, and then I'll write back

**Comment by cpsauer** [comment]
It looks like (internally) we've got a corrupted header include graph cache file for one reason or another.

If you can, to debug, could I ask you to print out the cache file that's causing this crash? One quick way to get the path (since it's sadly not already in the trace above) would be to temporarily it by going into the generated script (for me in in external/hedron_compile_commands/bazel-bin/refresh_all.py), and add a `print(cache_file_path)` just after `if os.path.isfile(cache_file_path):` And then `cat` that path and paste it here.

**Comment by cpsauer** [comment]
^ While that's very useful and would help us get to the root cause, if you can't easily figure out how to print out the bad cache file, you could also just try blowing away the caches with, e.g. `rm bazel-out/**/*.hedron.compile-commands.headers` (maybe run `ls bazel-out/**/*.hedron.compile-commands.headers` first!) and seeing if the error resolves comes back. `bazel clean` should also do it, but that'd clear out more of your cache than needed.

Offhand I'd guess maybe that it was just the result of, e.g., the process getting killed mid-cache-write or something, in which case deleting would fix it this time, but obviously I'd like to understand more and to make things more robust.

**Comment by lsmgeb89** [comment]
After adding that line, files ending with `compile-commands.headers` are printed out.
Checking the last one before the crash, it looks like the file is not corrupted.
In order to not show anything related to my workspace, I put the main structure here.
```text
["626e8cf3e4af6ed4af1aec8cf457fc681861e773600d7bf2f24266f5c42a6db3", ["xxx", "yyy", "zzz"]]
```
@cpsauer Please let me know if there is anything I can do to help you debug before I deleted these headers.

**Comment by cpsauer** [comment]
Hey Siming. Thanks for digging it out and staying with me.
That file definitely looks good and json decodable, but I think the error is indicating a file that's malformed json (and maybe empty?) with high enough probability that we should check to make sure that the file isn't from another thread.

Could I ask you to check the last several file paths that were printed out to see if any look like the wouldn't decode properly? Alternatively, to be sure, you could chance `threadpool.map` to `map` to turn off the multithreading to be sure that the issue comes from that last file path printed.

If everything still looks okay, could you then maybe boot up the Python interpreter and
`import json; json.load(<the path>)` to double check?

And if it looks wrong, I'd love to see it. If it's, e.g., half written, I'll make it handle that case better.

After you've done those additional cache checks, please go ahead and delete, and see if that fixes things. Again, thanks for being so thorough and patient--and sorry my code isn't doing the right thing.

-Chris

**Comment by lsmgeb89** [comment]
Checked the last 12 headers, and all look good.
And then changed `threadpool.map` to `map` to turn off multi-threading and retried.
It reproduced.
Checked the last three headers.
The last one is empty like you expected.
The last-second one looks like this: `["493817bc977cb257a0cb744587ee4871a50c6b18e970ee941502949e279ee3b9", []]`
The last-third one looks good.

After deleting these headers, the command succeeds.
Thanks for your quick response.

**Comment by cpsauer** [comment]
You're very welcome! Sorry we didn't have that corruption case handled well--and thank you so much for being great about helping debug.

I just pushed a commit that makes us recover from this case gracefully, repairing any caches that get messed up by, e.g., manual termination or crashes. Thanks for helping make it so no one else runs into this in the future!

Cheers,
Chris
