### ISSUE TITLE
NameError: name 'header_search_process' is not defined

### ISSUE THREAD

**Issue by dc6c** [hedronvision/bazel-compile-commands-extractor#94]
I'm trying out the extractor on the bazel c++ tutorial on Windows and VS2019.
Versions: bazel 5.1.0, bazel-compile-commands-extractor: a797a787e56fb766c8a900c3ed5a650ea45be844, Python 3.10.2

```
>bazel run @hedron_compile_commands//:refresh_all
INFO: Analyzed target @hedron_compile_commands//:refresh_all (3 packages loaded, 17 targets configured).
INFO: Found 1 target...
Target @hedron_compile_commands//:refresh_all up-to-date:
  bazel-bin/external/hedron_compile_commands/refresh_all.py
  bazel-bin/external/hedron_compile_commands/refresh_all.exe
  bazel-bin/external/hedron_compile_commands/refresh_all.zip
INFO: Elapsed time: 0.487s, Critical Path: 0.09s
INFO: 7 processes: 6 internal, 1 local.
INFO: Build completed successfully, 7 total actions
INFO: Build completed successfully, 7 total actions
>>> Analyzing commands used in @//...
WARNING: Running Bazel server needs to be killed, because the startup options are different.
WARNING: Waiting for server process to terminate (waited 5 seconds, waiting at most 60)
Starting local Bazel server and connecting to it...
Traceback (most recent call last):
  File "\\?\C:\Users\DAVORC~1\AppData\Local\Temp\Bazel.runfiles_7lcxv2bo\runfiles\hedron_compile_commands\refresh_all.py", line 1043, in <module>
    compile_command_entries.extend(_get_commands(target, flags))
  File "\\?\C:\Users\DAVORC~1\AppData\Local\Temp\Bazel.runfiles_7lcxv2bo\runfiles\hedron_compile_commands\refresh_all.py", line 918, in _get_commands
    yield from _convert_compile_commands(parsed_aquery_output)
  File "\\?\C:\Users\DAVORC~1\AppData\Local\Temp\Bazel.runfiles_7lcxv2bo\runfiles\hedron_compile_commands\refresh_all.py", line 809, in _convert_compile_commands
    for source_files, header_files, compile_command_args in outputs:
  File "C:\Python310\lib\concurrent\futures\_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Python310\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "\\?\C:\Users\DAVORC~1\AppData\Local\Temp\Bazel.runfiles_7lcxv2bo\runfiles\hedron_compile_commands\refresh_all.py", line 767, in _get_cpp_command_for_files
    source_files, header_files = _get_files(compile_action)
  File "\\?\C:\Users\DAVORC~1\AppData\Local\Temp\Bazel.runfiles_7lcxv2bo\runfiles\hedron_compile_commands\refresh_all.py", line 609, in _get_files
    header_files = _get_headers(compile_action, source_file)
  File "\\?\C:\Users\DAVORC~1\AppData\Local\Temp\Bazel.runfiles_7lcxv2bo\runfiles\hedron_compile_commands\refresh_all.py", line 530, in _get_headers
    headers = _get_headers_msvc(compile_action.arguments, source_path)
  File "\\?\C:\Users\DAVORC~1\AppData\Local\Temp\Bazel.runfiles_7lcxv2bo\runfiles\hedron_compile_commands\refresh_all.py", line 414, in _get_headers_msvc
    for line in header_search_process.stderr.splitlines():
NameError: name 'header_search_process' is not defined. Did you mean: '_header_search_process'?
```

**Comment by dc6c** [comment]
FWIW, I can see `_header_search_process` assigned at [line 378](https://github.com/hedronvision/bazel-compile-commands-extractor/blob/a797a787e56fb766c8a900c3ed5a650ea45be844/refresh.template.py#L378) in `_get_headers_msvc()`, and `header_search_process` used in the for-loop at [line ](https://github.com/hedronvision/bazel-compile-commands-extractor/blob/a797a787e56fb766c8a900c3ed5a650ea45be844/refresh.template.py#L408).

**Comment by cpsauer** [comment]
Hi, Davor. 

That's definitely on me. Sorry about that. [Sadly the first typo-type error to hit users in this repo 🙊] 

Thanks for reporting and tracing it down. I really appreciate the high quality, actionable issue. My only regret is that we didn't get you on the contributor board this time for your troubles!

Please lmk if you run into other problems!

Cheers,
Chris

**Comment by dc6c** [comment]
No problem, I'm happy to help (in a very small way) improve this very useful tool!

**Comment by cpsauer** [comment]
Thanks for the kind words. They're a key part of keeping it fun to maintain this and help people :)
